// 由 tools/blaze-extract/gen-protocol.mjs 从 CardTool.js 协议表生成，勿手改。
package com.bf1.admin.tool.blaze

data class BlazeErrorDef(val name: String, val description: String)

object BlazeProtocol {
    val components: Map<Int, String> = mapOf(
        0 to "Core",
        1 to "Authentication",
        3 to "Example",
        4 to "GameManager",
        5 to "Redirector",
        7 to "Stats",
        9 to "Util",
        10 to "CensusData",
        11 to "Clubs",
        15 to "Messaging",
        25 to "AssociationLists",
        27 to "GpsContentController",
        28 to "GameReporting",
        30 to "Matchmaker",
        31 to "ByteVault",
        33 to "Achievements",
        334 to "Greeter",
        401 to "Search",
        402 to "GameManagerMetrics",
        500 to "GamePacker",
        1002 to "NucleusIdentity",
        1003 to "NucleusConnect",
        1006 to "XBLProfile",
        1010 to "Notify",
        1020 to "XBLSocial",
        1021 to "XBLPrivacyConfigs",
        1022 to "XBLReputationConfigs",
        1023 to "XBLReputationService",
        1024 to "XBLServiceConfigs",
        1025 to "XBLSystemConfigs",
        1026 to "XBLClientSessionDirectory",
        1028 to "ArsonXblSessionDirectoryArena",
        1029 to "ArsonXBLOrganizerTournamentsHub",
        1030 to "CCS",
        1031 to "Friends",
        1035 to "SecretVault",
        1037 to "PAS",
        1099 to "Recommendation",
        2001 to "TestService",
        3000 to "PSNBaseUrl",
        3001 to "PSNSessionInvitation",
        3002 to "PSNMatches",
        3003 to "PSNSessionManager",
        3004 to "PsnAuthZ",
        4000 to "GdprCompliance",
        30722 to "UserSessions",
    )

    val commands: Map<String, Map<String, Map<Int, String>>> = mapOf(
        "Core" to mapOf(
        ),
        "Authentication" to mapOf(
            "Command" to mapOf(
                10 to "login",
                11 to "trustedLogin",
                29 to "listUserEntitlements2",
                30 to "getAccount",
                31 to "grantEntitlement",
                32 to "listEntitlements",
                34 to "getUseCount",
                35 to "decrementUseCount",
                39 to "grantEntitlement2",
                43 to "modifyEntitlement2",
                47 to "getPrivacyPolicyContent",
                48 to "listPersonaEntitlements2",
                52 to "getOptIn",
                53 to "enableOptIn",
                54 to "disableOptIn",
                60 to "expressLogin",
                61 to "stressLogin",
                70 to "logout",
                90 to "getPersona",
                100 to "listPersonas",
                230 to "createWalUserSession",
                240 to "checkLegalDoc",
                242 to "getEmailOptInSettings",
                246 to "getTermsOfServiceContent",
                260 to "getOriginPersona",
                290 to "guestLogin",
                300 to "getDecryptedBlazeIds",
            ),
        ),
        "GameManager" to mapOf(
            "Command" to mapOf(
                1 to "createGame",
                2 to "destroyGame",
                3 to "advanceGameState",
                4 to "setGameSettings",
                5 to "setPlayerCapacity",
                6 to "setPresenceMode",
                7 to "setGameAttributes",
                8 to "setPlayerAttributes",
                9 to "joinGame",
                10 to "createGameTemplate",
                11 to "removePlayer",
                15 to "finalizeGameCreation",
                16 to "startMatchmakingScenario",
                17 to "cancelMatchmakingScenario",
                18 to "setPlayerCustomData",
                19 to "replayGame",
                20 to "returnDedicatedServerToPool",
                21 to "setDedicatedServerAttributes",
                22 to "leaveGameByGroup",
                23 to "migrateGame",
                24 to "updateGameHostMigrationStatus",
                25 to "resetDedicatedServer",
                26 to "updateGameSession",
                27 to "banPlayer",
                28 to "matchmakingDedicatedServerOverride",
                29 to "updateMeshConnection",
                30 to "joinGameByUserList",
                31 to "removePlayerFromBannedList",
                32 to "clearBannedList",
                33 to "getBannedList",
                34 to "getMatchmakingDedicatedServerOverrides",
                35 to "matchmakingFillServersOverride",
                36 to "getMatchmakingFillServersOverride",
                38 to "addQueuedPlayerToGame",
                39 to "updateGameName",
                40 to "ejectHost",
                41 to "setGameModRegister",
                42 to "setGameEntryCriteria",
                43 to "preferredJoinOptOut",
                44 to "destroyGames",
                45 to "createOrJoinGame",
                46 to "requestPlatformHost",
                47 to "demoteReservedPlayerToQueue",
                50 to "createPseudoGame",
                51 to "createPseudoGames",
                52 to "cancelCreatePseudoGames",
                53 to "destroyAllPseudoGames",
                54 to "captureGameManagerEnvironment",
                55 to "isGameCaptureDone",
                56 to "getRedisDumpLocations",
                65 to "meshEndpointsConnected",
                66 to "meshEndpointsDisconnected",
                67 to "meshEndpointsConnectionLost",
                68 to "requestConnectivityViaCCS",
                69 to "freeConnectivityViaCCS",
                70 to "requestLeaseExtensionViaCCS",
                90 to "createTournamentGame",
                91 to "cancelTournamentGame",
                92 to "getTournamentGameStatus",
                98 to "getGameBrowserAttributesConfig",
                99 to "getGameListByScenario",
                100 to "getGameListSnapshot",
                101 to "getGameListSubscription",
                102 to "destroyGameList",
                103 to "getFullGameData",
                104 to "getMatchmakingConfig",
                105 to "getGameDataFromId",
                106 to "addAdminPlayer",
                107 to "removeAdminPlayer",
                108 to "getScenarioAttributesConfig",
                109 to "changeGameTeamId",
                110 to "migrateAdminPlayer",
                111 to "getUserSetGameListSubscription",
                112 to "swapPlayers",
                113 to "getGameDataByUser",
                114 to "getCreateGameTemplateAttributesConfig",
                152 to "getGameListSnapshotSync",
                153 to "findDedicatedServers",
                171 to "reportTelemetry",
                172 to "addUsersToConnectionMetricAudit",
                173 to "removeUsersFromConnectionMetricAudit",
                174 to "fetchAuditedUsers",
                175 to "fetchAuditedUserData",
                176 to "deleteUserAuditMetricData",
                177 to "updatePrimaryExternalSessionForUser",
                178 to "getScenarioDetails",
                200 to "startPseudoMatchmakingScenario",
                201 to "updateExternalSessionImage",
                202 to "updateExternalSessionStatus",
                203 to "setUserScenarioVariant",
                204 to "getScenarioVariants",
                205 to "clearUserScenarioVariant",
                206 to "getTemplatesAndAttributes",
                207 to "getScenariosAndAttributes",
            ),
            "Message" to mapOf(
                3 to "NotifyMatchmakingScenarioPseudoSuccess",
                10 to "NotifyMatchmakingFailed",
                11 to "NotifyMatchmakingSessionConnectionValidated",
                12 to "NotifyMatchmakingAsyncStatus",
                13 to "NotifyMatchmakingPseudoSuccess",
                14 to "NotifyRemoteMatchmakingStarted",
                15 to "NotifyRemoteMatchmakingEnded",
                16 to "NotifyGameRemoved",
                20 to "NotifyGameSetup",
                21 to "NotifyPlayerJoining",
                22 to "NotifyJoiningPlayerInitiateConnections",
                23 to "NotifyPlayerJoiningQueue",
                24 to "NotifyPlayerPromotedFromQueue",
                25 to "NotifyPlayerClaimingReservation",
                26 to "NotifyPlayerDemotedToQueue",
                30 to "NotifyPlayerJoinCompleted",
                40 to "NotifyPlayerRemoved",
                41 to "NotifyRemoteJoinFailed",
                60 to "NotifyHostMigrationFinished",
                70 to "NotifyHostMigrationStart",
                71 to "NotifyPlatformHostInitialized",
                80 to "NotifyGameAttribChange",
                81 to "NotifyDedicatedServerAttribChange",
                90 to "NotifyPlayerAttribChange",
                95 to "NotifyPlayerCustomDataChange",
                100 to "NotifyGameStateChange",
                110 to "NotifyGameSettingsChange",
                111 to "NotifyGameCapacityChange",
                112 to "NotifyGameReset",
                113 to "NotifyGameReportingIdChange",
                114 to "NotifyGamePresenceChanged",
                115 to "NotifyGameSessionUpdated",
                116 to "NotifyGamePlayerStateChange",
                117 to "NotifyGamePlayerTeamRoleSlotChange",
                118 to "NotifyGameTeamIdChange",
                119 to "NotifyProcessQueue",
                120 to "NotifyPresenceModeChanged",
                121 to "NotifyQueueChanged",
                123 to "NotifyGameModRegisterChanged",
                124 to "NotifyGameEntryCriteriaChanged",
                125 to "NotifyMatchmakingReservedExternalPlayers",
                135 to "NotifyHostedConnectivityAvailable",
                201 to "NotifyGameListUpdate",
                202 to "NotifyAdminListChange",
                230 to "NotifyGameNameChange",
                1016 to "NotifyGameRemoved",
                1020 to "NotifyGameSetup",
                1021 to "NotifyPlayerJoining",
                1022 to "NotifyJoiningPlayerInitiateConnections",
                1023 to "NotifyPlayerJoiningQueue",
                1024 to "NotifyPlayerPromotedFromQueue",
                1025 to "NotifyPlayerClaimingReservation",
                1026 to "NotifyPlayerDemotedToQueue",
                1030 to "NotifyPlayerJoinCompleted",
                1040 to "NotifyPlayerRemoved",
                1041 to "NotifyRemoteJoinFailed",
                1060 to "NotifyHostMigrationFinished",
                1070 to "NotifyHostMigrationStart",
                1071 to "NotifyPlatformHostInitialized",
                1080 to "NotifyGameAttribChange",
                1081 to "NotifyDedicatedServerAttribChange",
                1090 to "NotifyPlayerAttribChange",
                1095 to "NotifyPlayerCustomDataChange",
                1100 to "NotifyGameStateChange",
                1110 to "NotifyGameSettingsChange",
                1111 to "NotifyGameCapacityChange",
                1112 to "NotifyGameReset",
                1113 to "NotifyGameReportingIdChange",
                1114 to "NotifyGamePresenceChanged",
                1115 to "NotifyGameSessionUpdated",
                1116 to "NotifyGamePlayerStateChange",
                1117 to "NotifyGamePlayerTeamRoleSlotChange",
                1118 to "NotifyGameTeamIdChange",
                1119 to "NotifyProcessQueue",
                1120 to "NotifyPresenceModeChanged",
                1121 to "NotifyQueueChanged",
                1123 to "NotifyGameModRegisterChanged",
                1124 to "NotifyGameEntryCriteriaChanged",
                1202 to "NotifyAdminListChange",
                1230 to "NotifyGameNameChange",
                1240 to "NotifyMatchmakingFailed",
                1250 to "NotifyHostedConnectivityAvailable",
            ),
        ),
        "Redirector" to mapOf(
            "Command" to mapOf(
                1 to "getServerInstance",
                7 to "getServerAddressMap",
                9 to "getCACertificates",
                10 to "findCACertificates",
                11 to "publishServerInstanceInfo",
                12 to "updateServerInstanceInfo",
                14 to "getPeerServerAddress",
                15 to "getCAResolverMetrics",
                16 to "purgeServerRegistration",
                17 to "getServerInstanceHttp",
            ),
        ),
        "Stats" to mapOf(
            "Command" to mapOf(
                1 to "getStatDescs",
                2 to "getStats",
                3 to "getStatGroupList",
                4 to "getStatGroup",
                5 to "getStatsByGroup",
                6 to "getDateRange",
                7 to "getEntityCount",
                8 to "updateStats",
                9 to "wipeStats",
                10 to "getLeaderboardGroup",
                11 to "getLeaderboardFolderGroup",
                12 to "getLeaderboard",
                13 to "getCenteredLeaderboard",
                14 to "getFilteredLeaderboard",
                15 to "getKeyScopesMap",
                16 to "getStatsByGroupAsync",
                17 to "getLeaderboardTreeAsync",
                18 to "getLeaderboardEntityCount",
                19 to "getStatCategoryList",
                20 to "getPeriodIds",
                21 to "getLeaderboardRaw",
                22 to "getCenteredLeaderboardRaw",
                23 to "getFilteredLeaderboardRaw",
                24 to "changeKeyscopeValue",
                25 to "getEntityRank",
                26 to "initializeStatsTransaction",
                27 to "commitStatsTransaction",
                28 to "abortStatsTransaction",
                29 to "calcDerivedStats",
                30 to "retrieveValuesStats",
                162 to "getStatsByGroupAsync2",
                172 to "getLeaderboardTreeAsync2",
                212 to "getLeaderboardRaw2",
                222 to "getCenteredLeaderboardRaw2",
                232 to "getFilteredLeaderboardRaw2",
            ),
            "Message" to mapOf(
                1 to "UpdateCacheNotification",
                2 to "UpdateGlobalStatsNotification",
                50 to "GetStatsAsyncNotification",
                51 to "GetLeaderboardTreeNotification",
            ),
        ),
        "Util" to mapOf(
            "Command" to mapOf(
                1 to "fetchClientConfig",
                2 to "ping",
                3 to "setClientData",
                4 to "localizeStrings",
                5 to "getTelemetryServer",
                6 to "getTickerServer",
                7 to "preAuth",
                8 to "postAuth",
                10 to "userSettingsLoad",
                11 to "userSettingsSave",
                12 to "userSettingsLoadAll",
                13 to "userSettingsLoadAllForUserId",
                14 to "deleteUserSettings",
                15 to "userSettingsLoadMultiple",
                20 to "filterForProfanity",
                21 to "setClientMetrics",
                23 to "setConnectionState",
                25 to "getUserOptions",
                26 to "setUserOptions",
                27 to "suspendUserPing",
                28 to "setClientState",
                29 to "setClientUserMetrics",
            ),
        ),
        "Messaging" to mapOf(
            "Command" to mapOf(
                1 to "sendMessage",
                2 to "fetchMessages",
                3 to "purgeMessages",
                4 to "touchMessages",
                5 to "getMessages",
                6 to "sendSourceMessage",
                7 to "sendGlobalMessage",
            ),
            "Message" to mapOf(
                1 to "NotifyMessage",
            ),
        ),
        "AssociationLists" to mapOf(
            "Command" to mapOf(
                1 to "addUsersToList",
                2 to "removeUsersFromList",
                3 to "clearLists",
                4 to "setUsersToList",
                5 to "getListForUser",
                6 to "getLists",
                7 to "subscribeToLists",
                8 to "unsubscribeFromLists",
                9 to "getConfigListsInfo",
                10 to "getMemberHash",
                11 to "checkListMembership",
                12 to "checkListContainsMembers",
                13 to "setUsersAttributesInList",
            ),
        ),
        "GameReporting" to mapOf(
            "Command" to mapOf(
                1 to "submitGameReport",
                2 to "submitOfflineGameReport",
                3 to "submitGameEvents",
                4 to "getGameReportQuery",
                5 to "getGameReportQueriesList",
                6 to "getGameReports",
                7 to "getGameReportView",
                8 to "getGameReportViewInfo",
                9 to "getGameReportViewInfoList",
                10 to "getGameReportTypes",
                11 to "updateMetric",
                12 to "getGameReportColumnInfo",
                13 to "getGameReportColumnValues",
                14 to "getTournamentGameReportView",
                100 to "submitTrustedMidGameReport",
                101 to "submitTrustedEndGameReport",
                200 to "gameStarted",
                201 to "gameFinished",
            ),
        ),
        "Matchmaker" to mapOf(
            "Command" to mapOf(
                1 to "startMatchmakingInternal",
                2 to "cancelMatchmakingInternal",
                10 to "getMatchmakingConfig",
                11 to "getMatchmakingInstanceStatus",
                33 to "matchmakingDedicatedServerOverride",
                34 to "getMatchmakingDedicatedServerOverrides",
                35 to "matchmakingFillServersOverride",
                36 to "getMatchmakingFillServersOverride",
                41 to "gameSessionConnectionComplete",
                42 to "getMatchmakingMetrics",
            ),
        ),
        "Achievements" to mapOf(
            "Command" to mapOf(
                1 to "getAchievements",
                3 to "grantAchievement",
                6 to "postEvents",
            ),
        ),
        "Friends" to mapOf(
            "Command" to mapOf(
                1 to "muteUser",
                2 to "checkMuteStatus",
                3 to "unmuteUser",
            ),
        ),
        "UserSessions" to mapOf(
            "Command" to mapOf(
                1 to "validateSessionKey",
                3 to "fetchExtendedData",
                5 to "updateExtendedDataAttribute",
                8 to "updateHardwareFlags",
                9 to "getPermissions",
                10 to "getAccessGroup",
                12 to "lookupUser",
                13 to "lookupUsers",
                14 to "lookupUsersByPrefix",
                15 to "lookupUsersIdentification",
                20 to "updateNetworkInfo",
                21 to "listDefaultAccessGroup",
                22 to "listAuthorization",
                23 to "lookupUserGeoIPData",
                24 to "overrideUserGeoIPData",
                25 to "updateUserSessionClientData",
                26 to "setUserInfoAttribute",
                27 to "resetUserGeoIPData",
                28 to "lookupEntityByName",
                29 to "lookupEntityById",
                30 to "lookupEntitiesByIds",
                31 to "registerRemoteSlaveSession",
                32 to "lookupUserSessionId",
                33 to "fetchLastLocaleUsedAndAuthError",
                34 to "fetchUserFirstLastAuthTime",
                36 to "listAllPermissions",
                37 to "setUserGeoOptIn",
                38 to "remoteLoadUserExtendedData",
                39 to "remoteRefreshUserExtendedData",
                40 to "forceSessionLogout",
                41 to "enableUserAuditLogging",
                42 to "disableUserAuditLogging",
                43 to "requestUserExtendedDataProviderRegistration",
                44 to "getUserGeoIpData",
                45 to "getUniqueDeviceId",
                46 to "getIpFilterByName",
                47 to "lookupUsersByPrefixMultiNamespace",
                48 to "lookupUsersByPersonaNameMultiNamespace",
                49 to "lookupUsersByPersonaNamesMultiNamespace",
                50 to "lookupUsersByPersonaNames",
                53 to "checkConnectivity",
                54 to "forceOwnSessionLogout",
                55 to "updateLocalUserGroup",
                56 to "fetchUsersAuditState",
                57 to "refreshQosPingSiteMap",
                58 to "getQosPingSites",
                60 to "setUserCrossPlatformOptIn",
                61 to "lookupUsersCrossPlatform",
                62 to "getDeviceLocality",
                100 to "getUedInformationMap",
            ),
            "Message" to mapOf(
                1 to "UserSessionExtendedDataUpdate",
                2 to "UserAdded",
                3 to "UserRemoved",
                5 to "UserUpdated",
                6 to "UserSubscriptionsUpdated",
                7 to "SessionSubscriptionsUpdated",
                8 to "UserAuthenticated",
                9 to "UserUnauthenticated",
                10 to "NotifyUserInfoUpdated",
                11 to "NotifyQosSettingsUpdated",
            ),
        ),
    )

    val errors: Map<String, Map<Int, BlazeErrorDef>> = mapOf(
        "Core" to mapOf(
            1 to BlazeErrorDef("ERR_SYSTEM", "General system error."),
            2 to BlazeErrorDef("ERR_COMPONENT_NOT_FOUND", "Component not found."),
            3 to BlazeErrorDef("ERR_COMMAND_NOT_FOUND", "Command not found."),
            4 to BlazeErrorDef("ERR_AUTHENTICATION_REQUIRED", "This command requires you to log in/provide access credentials."),
            5 to BlazeErrorDef("ERR_TIMEOUT", "Command timed out."),
            6 to BlazeErrorDef("ERR_DISCONNECTED", "Calling session got disconnected."),
            7 to BlazeErrorDef("ERR_DUPLICATE_LOGIN", "Duplicate user has logged in."),
            8 to BlazeErrorDef("ERR_AUTHORIZATION_REQUIRED", "You don't have the required permission to perform the action."),
            9 to BlazeErrorDef("ERR_CANCELED", "The job, fiber or action has been canceled."),
            10 to BlazeErrorDef("ERR_CUSTOM_REQUEST_HOOK_FAILED", "General error thrown by a RPC's custom request hook, triggered by custom code."),
            11 to BlazeErrorDef("ERR_CUSTOM_RESPONSE_HOOK_FAILED", "General error thrown by a RPC's custom response hook, triggered by custom code."),
            12 to BlazeErrorDef("ERR_TDF_STRING_TOO_LONG", "General error thrown by TDF decoder when incoming string exceeds max length defined for this field in TDF"),
            13 to BlazeErrorDef("ERR_INVALID_TDF_ENUM_VALUE", "General error thrown by TDF decoder when incoming enum value is not a defined enum for this field in TDF"),
            14 to BlazeErrorDef("ERR_MOVED", "The command must be executed on a Blaze instance that owns the object refered to by the request."),
            16 to BlazeErrorDef("ERR_COMMAND_FIBERS_MAXED_OUT", "The command fibers have hit the max limit."),
            17 to BlazeErrorDef("ERR_INVALID_ENDPOINT", "The command has come on the wrong endpoint."),
            18 to BlazeErrorDef("ERR_TDF_STRING_NOT_UTF8", "General error thrown by TDF encoder on client when string is not valid utf8."),
            19 to BlazeErrorDef("ERR_UNAVAILABLE", "The service is currently unavailable. This is most likely a transient condition and may be corrected by retrying with a backoff."),
            20 to BlazeErrorDef("ERR_NOT_PRIMARY_PERSONA", "Action only allowed for a primary persona."),
            101 to BlazeErrorDef("ERR_DB_SYSTEM", "General DB error"),
            102 to BlazeErrorDef("ERR_DB_NOT_CONNECTED", "Not connected to the DB"),
            103 to BlazeErrorDef("ERR_DB_NOT_SUPPORTED", "Operation not supported"),
            104 to BlazeErrorDef("ERR_DB_NO_CONNECTION_AVAILABLE", "No connection could be obtained"),
            105 to BlazeErrorDef("ERR_DB_DUP_ENTRY", "A duplicate entry already exists in the DB"),
            106 to BlazeErrorDef("ERR_DB_NO_SUCH_TABLE", "Table does not exist"),
            107 to BlazeErrorDef("ERR_DB_DISCONNECTED", "Lost connection to DB"),
            108 to BlazeErrorDef("ERR_DB_TIMEOUT", "Request timed out"),
            109 to BlazeErrorDef("ERR_DB_INIT_FAILED", "Driver initialization failed"),
            110 to BlazeErrorDef("ERR_DB_TRANSACTION_NOT_COMPLETE", "Connection was released while a transaction was pending"),
            111 to BlazeErrorDef("ERR_DB_LOCK_DEADLOCK", "Deadlock"),
            112 to BlazeErrorDef("ERR_DB_DROP_PARTITION_NON_EXISTENT", "Non existent partition"),
            113 to BlazeErrorDef("ERR_DB_SAME_NAME_PARTITION", "Partition already exists"),
            114 to BlazeErrorDef("ERR_SERVER_BUSY", "**Deprecated - use ERR_TIMEOUT instead** The server is too busy to process this request.  Please try again later."),
            115 to BlazeErrorDef("ERR_GUEST_SESSION_NOT_ALLOWED", "This error will be returned when a guest session tries to call a RPC which is not allowed guest session to call."),
            116 to BlazeErrorDef("ERR_DB_USER_DEFINED_EXCEPTION", "The user defined error."),
            117 to BlazeErrorDef("ERR_COULDNT_CONNECT", "Could not connect to external service when making request. Equivalent to curl error (7)."),
            118 to BlazeErrorDef("ERR_DB_PREVIOUS_TRANSACTION_IN_PROGRESS", "A transaction is already in progress"),
            119 to BlazeErrorDef("ERR_DB_NO_ROWS_AFFECTED", "No rows were affected as a result of the query."),
            120 to BlazeErrorDef("ERR_DB_NO_SUCH_THREAD", "No such db thread"),
        ),
        "Authentication" to mapOf(
            1 to BlazeErrorDef("AUTH_ERR_INVALID_TOKEN", "The token provided was not a valid Identity 2.0 access token"),
            2 to BlazeErrorDef("AUTH_ERR_INVALID_REQUEST", "Generic error if specific error could not be obtained for a failed request."),
            3 to BlazeErrorDef("AUTH_ERR_INVALID_AUTHCODE", "The auth code provided could not be used to log to requested service."),
            4 to BlazeErrorDef("AUTH_ERR_INVALID_PLATFORM", "The platform that service belongs to is not allowed in the login command."),
            6 to BlazeErrorDef("AUTH_ERR_INVALID_SANDBOX_ID", "The supplied sandbox id is not supported on this server."),
            10 to BlazeErrorDef("AUTH_ERR_INVALID_COUNTRY", "The country does not exist or is invalid"),
            11 to BlazeErrorDef("AUTH_ERR_INVALID_USER", "The user does not exist or is invalid"),
            12 to BlazeErrorDef("AUTH_ERR_INVALID_PASSWORD", "The supplied password was invalid"),
            14 to BlazeErrorDef("AUTH_ERR_EXPIRED_TOKEN", "The supplied auth token was expired"),
            15 to BlazeErrorDef("AUTH_ERR_EXISTS", "Cannot create user/persona because email/displayname already exists"),
            16 to BlazeErrorDef("AUTH_ERR_TOO_YOUNG", "User is too young, cannot create underage account"),
            17 to BlazeErrorDef("AUTH_ERR_NO_ACCOUNT", "The account does not exist"),
            18 to BlazeErrorDef("AUTH_ERR_PERSONA_NOT_FOUND", "The requested persona name was not found."),
            19 to BlazeErrorDef("AUTH_ERR_PERSONA_INACTIVE", "The requested persona is not active."),
            20 to BlazeErrorDef("AUTH_ERR_INVALID_PMAIL", "Invalid parental email."),
            21 to BlazeErrorDef("AUTH_ERR_INVALID_FIELD", "One of the input fields was invalid"),
            22 to BlazeErrorDef("AUTH_ERR_INVALID_EMAIL", "Invalid email"),
            23 to BlazeErrorDef("AUTH_ERR_INVALID_STATUS", "Invalid account status"),
            32 to BlazeErrorDef("AUTH_ERR_PERSONA_BANNED", "The requested persona is banned."),
            33 to BlazeErrorDef("AUTH_ERR_INVALID_PERSONA", "The persona does not exist or is invalid"),
            34 to BlazeErrorDef("AUTH_ERR_CURRENT_PASSWORD_REQUIRED", "The command required the current password of the Nucleus account, the password provided is incorrect."),
            41 to BlazeErrorDef("AUTH_ERR_DEACTIVATED", "Account deactivated"),
            43 to BlazeErrorDef("AUTH_ERR_BANNED", "Account banned from online play"),
            44 to BlazeErrorDef("AUTH_ERR_DISABLED", "Account has been disabled"),
            45 to BlazeErrorDef("AUTH_ERR_DUPLICATE_LOGIN", "Account is already logged in with a different persona."),
            46 to BlazeErrorDef("AUTH_ERR_RESTRICTION_VIOLATION", "There was a restriction violation on a product"),
            47 to BlazeErrorDef("AUTH_ERR_MULTIPLE_WALLET_ACCOUNTS_FOUND", "More than one wallet was found."),
            48 to BlazeErrorDef("AUTH_ERR_INVALID_PRODUCT_CONFIGURATION", "The product is not configured correctly in the catalog"),
            49 to BlazeErrorDef("AUTH_ERR_ENTITLEMENT_TAG_MISSING", "The product in the catalog does not have an entitlement tag defined"),
            50 to BlazeErrorDef("AUTH_ERR_BAD_GATEWAY", "Received an invalid response from the upstream server"),
            54 to BlazeErrorDef("AUTH_ERR_NO_ASSOCIATED_PRODUCT", "No Associated product for this key"),
            55 to BlazeErrorDef("AUTH_ERR_INVALID_MAPPING_ERROR", "Invalid Mapping"),
            56 to BlazeErrorDef("AUTH_ERR_NO_SUCH_GROUP_NAME", "Group name not found"),
            57 to BlazeErrorDef("AUTH_ERR_MISSING_PERSONAID", "Missing personaId"),
            58 to BlazeErrorDef("AUTH_ERR_USER_DOES_NOT_MATCH_PERSONA", "User not match with persona"),
            59 to BlazeErrorDef("AUTH_ERR_WHITELIST", "Group name failed whilelist test"),
            60 to BlazeErrorDef("AUTH_ERR_LINK_PERSONA", "Failed linking persona and entitlement"),
            61 to BlazeErrorDef("AUTH_ERR_NO_SUCH_GROUP", "No such group"),
            63 to BlazeErrorDef("AUTH_ERR_NO_SUCH_ENTITLEMENT", "No active entitlement matching the criteria"),
            66 to BlazeErrorDef("AUTH_ERR_USECOUNT_ZERO", "The use count for the user's entitlement is 0"),
            67 to BlazeErrorDef("AUTH_ERR_ENTITLEMETNTAG_EMPTY", "The entitlement tag is required but it's empty string in requirement"),
            70 to BlazeErrorDef("AUTH_ERR_GROUPNAME_REQUIRED", "Groupname is required"),
            71 to BlazeErrorDef("AUTH_ERR_GROUPNAME_INVALID", "A groupname in group list is empty string"),
            72 to BlazeErrorDef("AUTH_ERR_TOO_MANY_ENTITLEMENTS", "Too many entitlements were found in Nucleus. Requestor should use pagination to fetch smaller result sets."),
            73 to BlazeErrorDef("AUTH_ERR_PAGESIZE_ZERO", "Page size in the request can't be 0"),
            74 to BlazeErrorDef("AUTH_ERR_ENTITLEMENT_TAG_REQUIRED", "Entitlement tag is required"),
            75 to BlazeErrorDef("AUTH_ERR_PAGENO_ZERO", "Page No in the request can't be 0"),
            76 to BlazeErrorDef("AUTH_ERR_MODIFIED_STATUS_INVALID", "You only can modify an entitlement status to DISABLED, DELETED or BANNED"),
            77 to BlazeErrorDef("AUTH_ERR_USECOUNT_INCREMENT", "You only can decrement the use count and can not increment it"),
            78 to BlazeErrorDef("AUTH_ERR_TERMINATION_INVALID", "You can't make the termination date LATER, than it is currently.  You can make it sooner"),
            79 to BlazeErrorDef("AUTH_ERR_UNKNOWN_ENTITLEMENT", "The entitlement doesn't exist"),
            80 to BlazeErrorDef("AUTH_ERR_EXCEEDS_PSU_LIMIT", "PSU cutoff for entitlement type is less than the current connected user count"),
            81 to BlazeErrorDef("AUTH_ERR_OPTIN_NAME_REQUIRED", "The opt-in name is required"),
            82 to BlazeErrorDef("AUTH_ERR_INVALID_OPTIN", "The provided opt-in is invalid "),
            83 to BlazeErrorDef("AUTH_ERR_OPTIN_MISMATCH", "German double opt in cannot be set to true if global opt in is not set to true as well"),
            84 to BlazeErrorDef("AUTH_ERR_NO_SUCH_OPTIN", "The user has not opted in for the given optInType"),
            85 to BlazeErrorDef("AUTH_ERR_AUTHID_REQUIRED", "The ID of the external authentication data is required"),
            86 to BlazeErrorDef("AUTH_ERR_PERSONA_EXTREFID_REQUIRED", "The ID for the persona external reference is required"),
            87 to BlazeErrorDef("AUTH_ERR_SOURCE_REQUIRED", "The requestor/game that is adding the external authentication is required"),
            88 to BlazeErrorDef("AUTH_ERR_APPLICATION_REQUIRED", "The application ID or other identifier associated with the external authentication token is required"),
            89 to BlazeErrorDef("AUTH_ERR_TOKEN_REQUIRED", "The token associated with the external authentication is required"),
            90 to BlazeErrorDef("AUTH_ERR_PARAMETER_TOO_LENGTH", "The input parameter exceeds the max value (255) on the server"),
            91 to BlazeErrorDef("AUTH_ERR_NO_SUCH_PERSONA_REFERENCE", "The persona external reference does not exist"),
            93 to BlazeErrorDef("AUTH_ERR_INVALID_SOURCE", "Invalid source provided. The source doesn't exist in the system"),
            94 to BlazeErrorDef("AUTH_ERR_NO_SUCH_AUTH_DATA", "The authentication data does not exist"),
            95 to BlazeErrorDef("AUTH_ERR_NOT_PRIMARY_PERSONA", "Account already has primary persona and updating primary via authentication is not allowed at this time."),
            101 to BlazeErrorDef("AUTH_ERR_USER_INACTIVE", "User's status is inactive (disabled, banned, etc.)"),
            102 to BlazeErrorDef("AUTH_ERR_UNEXPECTED_ACTIVATION", "User isn't awaiting activation."),
            103 to BlazeErrorDef("AUTH_ERR_NAME_MISMATCH", "User's display name doesn't match gamer tag."),
            105 to BlazeErrorDef("AUTH_ERR_INVALID_NAMESPACE", "The supplied namespace was invalid."),
            198 to BlazeErrorDef("AUTH_ERR_FIELD_MIN_LOWER_CHARS", "The value contains invalid characters."),
            199 to BlazeErrorDef("AUTH_ERR_FIELD_MIN_UPPER_CHARS", "The value is too short."),
            200 to BlazeErrorDef("AUTH_ERR_FIELD_MIN_DIGITS", "The value is too long."),
            201 to BlazeErrorDef("AUTH_ERR_FIELD_INVALID_CHARS", "The value contains invalid characters."),
            202 to BlazeErrorDef("AUTH_ERR_FIELD_TOO_SHORT", "The value is too short."),
            204 to BlazeErrorDef("AUTH_ERR_FIELD_MUST_BEGIN_WITH_LETTER", "The value must begin with a letter."),
            205 to BlazeErrorDef("AUTH_ERR_FIELD_MISSING", "The value is missing."),
            206 to BlazeErrorDef("AUTH_ERR_FIELD_INVALID", "The value is not valid for this field."),
            207 to BlazeErrorDef("AUTH_ERR_FIELD_NOT_ALLOWED", "The value contains profanity or disallowed text."),
            208 to BlazeErrorDef("AUTH_ERR_FIELD_NEEDS_SPECIAL_CHARS", "The value must contain special characters."),
            209 to BlazeErrorDef("AUTH_ERR_FIELD_ALREADY_EXISTS", "The value already exists."),
            210 to BlazeErrorDef("AUTH_ERR_FIELD_NEEDS_CONSENT", "The user requires parental consent."),
            211 to BlazeErrorDef("AUTH_ERR_FIELD_TOO_YOUNG", "The user is too young to create an account."),
            212 to BlazeErrorDef("AUTH_ERR_ASSOCIATION_TOO_YOUNG", "The associated user is too young, cannot associate with the new created account."),
            300 to BlazeErrorDef("AUTH_ERR_TOO_MANY_PERSONA_FOR_NAMESPACE", "The maximum number of personas in this namespace has been reached for this account. Cannot create additional personas."),
            303 to BlazeErrorDef("AUTH_ERR_NEEDS_PMAIL", "The user requires parental mail."),
            307 to BlazeErrorDef("AUTH_ERR_NO_PARENT_SESSION", "A parent session is required to create a guest MLU session but was not found."),
            308 to BlazeErrorDef("AUTH_ERR_NO_XBLTOKEN", "No XBL token is available for the user. This is likely due to the user being externally available in MS, but not 'known' to Nucleus."),
            309 to BlazeErrorDef("AUTH_ERR_NO_PSNTOKEN", "No PSN token is available for the user. This is likely due to the user being externally available in PSN, but not 'known' to Nucleus."),
            310 to BlazeErrorDef("AUTH_ERR_TRIAL_PERIOD_CLOSED", "Attempting to grant an entitlement outside the trial period. For period trials, this means the current time is outside the start/end time. For managed lifecycle, this means we attempt to grant an entitlement with a status that doesn't match based on the start/end time (PENDING, ACTIVE, DISABLED for before, during, and after, respectively.)"),
            311 to BlazeErrorDef("AUTH_ERR_EXPIRED_1PTOKEN", "The first party token expired for the user. The user may need to relogin to Nucleus with a new token."),
        ),
        "GameManager" to mapOf(
            1 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_SETTINGS", "A generic problem with the combination of game settings you're trying to use.  For example, you might be trying to change a game's ranked setting on the 360 after game creation (not allowed by XBL)."),
            2 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_ID", "The blazeServer wasn't able to find a game with the supplied gameId."),
            3 to BlazeErrorDef("GAMEMANAGER_ERR_JOIN_METHOD_NOT_SUPPORTED", "The player's game join failed because the game doesn't allow players to join using the supplied JoinMethod."),
            4 to BlazeErrorDef("GAMEMANAGER_ERR_PARTICIPANT_SLOTS_FULL", "The game doesn't have enough available participant slots. Note: If you need a public slot and none are available, you'll get PARTICIPANT_SLOTS_FULL, even if there are open private slots."),
            5 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_STATE_TRANSITION", "The game refused to change state because it would violate the GameState state machine's allowed transitions."),
            6 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_STATE_ACTION", "This RPC cannot be issued while the game is in its current state (GameState)."),
            7 to BlazeErrorDef("GAMEMANAGER_ERR_FAILED_IN_GAME_DESTROY", "System error: a game couldn't be destroyed for an unknown reason."),
            8 to BlazeErrorDef("GAMEMANAGER_ERR_QUEUE_FULL", "The game is full, and there's not enough room in the game's queue for you (or your entire group would overflow the queue)."),
            9 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_ENTRY_CRITERIA", "The game failed to parse the game entry criteria."),
            10 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_PROTOCOL_VERSION_MISMATCH", "There was a mismatch in game protocol versions"),
            11 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_IN_PROGRESS", "The game has already started, and does not allow join in progress."),
            12 to BlazeErrorDef("GAMEMANAGER_ERR_RESERVED_GAME_ID_INVALID", "DEPRECATED - Reserved ids are only allowed if dynamically created dedicated server mode is enabled and the ID isn't already taken by an existing game."),
            13 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_JOIN_METHOD", "The join method specified is not valid for the type of join attempted. System join methods not allowed, as well as specifying JOIN_BY_PLAYER with no player information(joinByGameId)"),
            14 to BlazeErrorDef("GAMEMANAGER_ERR_SLOT_OCCUPIED", "The requested slot was occupied- should only occur when attempting to join a specific slot in a game."),
            15 to BlazeErrorDef("GAMEMANAGER_ERR_NOT_VIRTUAL_GAME", "The requested action can only be performed on a virtualized game."),
            16 to BlazeErrorDef("GAMEMANAGER_ERR_NOT_TOPOLOGY_HOST", "The player requesting this action must be the topology host of the game."),
            17 to BlazeErrorDef("GAMEMANAGER_ERR_TOPOLOGY_NOT_SUPPORTED", "The requested network topology is not supported by the game type."),
            18 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_BUSY", "The join cannot be completed while the game is in a busy GameState or locked as busy. Callers may try again later."),
            19 to BlazeErrorDef("GAMEMANAGER_ERR_SESSION_TEMPLATE_NOT_SUPPORTED", "The requested external session template name is not supported by the server."),
            20 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_MODE_ATTRIBUTE_MISSING", "A game create or reset attempt didn't specify the game mode attribute."),
            21 to BlazeErrorDef("GAMEMANAGER_ERR_FAILED_DUE_TO_FRIENDS_ONLY_RESTRICTION", "The game's join restrictions prevented the user from joining."),
            22 to BlazeErrorDef("GAMEMANAGER_ERR_FAILED_DUE_TO_PRESENCE_MODE_RESTRICTION", "The game's presence mode prevented the user from joining."),
            23 to BlazeErrorDef("GAMEMANAGER_ERR_SPECTATOR_SLOTS_FULL", "The game doesn't have enough available spectator slots. Note: If you need a public slot and none are available, you'll get SPECTATOR_SLOTS_FULL, even if there are open private slots."),
            24 to BlazeErrorDef("GAMEMANAGER_ERR_UNRESPONSIVE_GAME_STATE", "This RPC cannot be issued while the game is in its current state (GameState == UNRESPONSIVE)."),
            25 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_DESTROYED_BY_CONNECTION_UPDATE", "The game was destroyed by the connection update. This is not an unexpected error, but must be handled differently from a ERR_OK. (Pointers to the Game may be invalidated.)"),
            26 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_PING_SITE_ALIAS", "The ping site alias provided for the dedicated server game was invalid or unknown to QoS."),
            27 to BlazeErrorDef("GAMEMANAGER_ERR_CROSSPLAY_DISABLED", "The crossplay settings of the Game or Request prevent the action from occurring."),
            28 to BlazeErrorDef("GAMEMANAGER_ERR_CROSSPLAY_DISABLED_USER", "The crossplay settings of the User prevent the action from occurring.  Can be fixed by changing the Crossplay Enabled setting of the User."),
            29 to BlazeErrorDef("GAMEMANAGER_ERR_UNEXPECTED_JOIN_FAILURE_GAME_VERSION", "Unexpected game record version detected while trying to join the game."),
            30 to BlazeErrorDef("GAMEMANAGER_ERR_PERMISSION_DENIED", "You must have admin rights on the game to issue this RPC."),
            31 to BlazeErrorDef("GAMEMANAGER_ERR_ALREADY_ADMIN", "A player to be added to admin list is already an admin."),
            32 to BlazeErrorDef("GAMEMANAGER_ERR_NOT_IN_ADMIN_LIST", "A player to be removed from admin list is actually not an admin."),
            33 to BlazeErrorDef("GAMEMANAGER_ERR_DEDICATED_SERVER_HOST", "A player to be removed from admin list is host of dedicated server, can't be removed."),
            50 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_QUEUE_METHOD", "The server configured queueing method does not allow this call to be made."),
            51 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_NOT_IN_QUEUE", "The player that is being added to the game from the queue, is not currently in the queue."),
            52 to BlazeErrorDef("GAMEMANAGER_ERR_DEQUEUE_WHILE_MIGRATING", "The server will not process a queued player while the game is migrating.  This is because the player will then fail to establish network connecitons."),
            53 to BlazeErrorDef("GAMEMANAGER_ERR_DEQUEUE_WHILE_IN_PROGRESS", "The server will not process a queued player while the game is in progress and in progress joins are not allowed."),
            101 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_NOT_FOUND", "The player wasn't found in a game, or the player may not exist at all (Note: we don't hit the user DB to validate a user's existence)."),
            103 to BlazeErrorDef("GAMEMANAGER_ERR_ALREADY_GAME_MEMBER", "The player can't join the game; he's already a game member"),
            104 to BlazeErrorDef("GAMEMANAGER_ERR_REMOVE_PLAYER_FAILED", "System Error: a player was banned from the game, but couldn't be removed."),
            107 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_PLAYER_PASSEDIN", "Attempting to take an action on an existing (but invalid) player.  For example, banning or kicking yourself out of a game."),
            108 to BlazeErrorDef("GAMEMANAGER_ERR_JOIN_PLAYER_FAILED", "A Dedicated server reset attempt failed because we couldn't join the game after resetting it."),
            109 to BlazeErrorDef("GAMEMANAGER_ERR_MISSING_PRIMARY_LOCAL_PLAYER", "The primry local player is not fully in game, so the other local users cannot join."),
            110 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_BANNED", "The player's joinGame failed; he's been banned from this game."),
            111 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_ENTRY_CRITERIA_FAILED", "The player's joinGame failed; he doesn't satisfy the game's EntryCriteria formula.  See the JoinGameCb's entry criteria string for details."),
            112 to BlazeErrorDef("GAMEMANAGER_ERR_ALREADY_IN_QUEUE", "The player can't join the game; they are already in the queue."),
            113 to BlazeErrorDef("GAMEMANAGER_ERR_ENFORCING_SINGLE_GROUP_JOINS", "The player can't join the game; the game's GameSettings::setEnforceSingleGroupJoin flag is set and the game already has 2 game groups in it."),
            114 to BlazeErrorDef("GAMEMANAGER_ERR_BANNED_PLAYER_NOT_FOUND", "The player isn't found in the banned list of the game, remove the banned player failure."),
            115 to BlazeErrorDef("GAMEMANAGER_ERR_BANNED_LIST_MAX", "The banned players have exceed the max banned users numable that setting at configuration file."),
            117 to BlazeErrorDef("GAMEMANAGER_ERR_FAILED_REPUTATION_CHECK", "The player failed to pass the reputation check on a game that doesn't allow any reputation value."),
            120 to BlazeErrorDef("GAMEMANAGER_ERR_RESERVATION_ALREADY_EXISTS", "The player cannot make a reservation for a game they already have a reservation in."),
            121 to BlazeErrorDef("GAMEMANAGER_ERR_NO_RESERVATION_FOUND", "The player can only claim reservations in a game in which they have made a reservation."),
            122 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GAME_ENTRY_TYPE", "The type of entry requested is not valid for the join method.  Matchmaking does not allow claiming reservations."),
            151 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_GROUP_ID", "The blazeServer wasn't able to find a user group with the supplied id."),
            152 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_NOT_IN_GROUP", "The player is not a member of the specified group."),
            200 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_MATCHMAKING_CRITERIA", "Problem parsing your matchmaking criteria.  See StartMatchmakingError's err msg for details."),
            201 to BlazeErrorDef("GAMEMANAGER_ERR_UNKNOWN_MATCHMAKING_SESSION_ID", "No matchmaking sessions exist with the id you specified."),
            202 to BlazeErrorDef("GAMEMANAGER_ERR_NOT_MATCHMAKING_SESSION_OWNER", "You can only cancel matchmaking sessions that you are the owner of."),
            203 to BlazeErrorDef("GAMEMANAGER_ERR_MATCHMAKING_NO_JOINABLE_GAMES", "None of the games provided from find game matchmaking were joinable."),
            205 to BlazeErrorDef("GAMEMANAGER_ERR_MATCHMAKING_USERSESSION_NOT_FOUND", "The owning user session for the session was not found."),
            206 to BlazeErrorDef("GAMEMANAGER_ERR_MATCHMAKING_EXCEEDED_MAX_REQUESTS", "The number of concurrent active matchmaking sessions exceeded configured maximum."),
            207 to BlazeErrorDef("GAMEMANAGER_ERR_MATCHMAKING_USER_GROUP_EXCEEDED_MAX_REQUESTS", "The number of concurrent active user group matchmaking sessions exceeded configured maximum."),
            230 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_CAPACITY_TOO_SMALL", "The capacity changes are invalid, it's less than current players count of the game, or the minimum capacity."),
            231 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_CAPACITY_TOO_LARGE", "The capacity changes are invalid, it's above the maximum players capacity of the game."),
            232 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_CAPACITY_IS_ZERO", "The capacity changes are invalid, the total participant count can't be 0."),
            233 to BlazeErrorDef("GAMEMANAGER_ERR_MAX_PLAYER_CAPACITY_TOO_LARGE", "The blazeServer has a compile-time limit of SLOT_ID_MAX_COUNT players in a game (256 by default).  See gamesessionmaster.h on the server."),
            250 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_TEAM_CAPACITIES_VECTOR_SIZE", "A game must have 1 or more teams specified."),
            251 to BlazeErrorDef("GAMEMANAGER_ERR_DUPLICATE_TEAM_CAPACITY", "vector contains multiple nodes for a single teamId."),
            252 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_TEAM_ID_IN_TEAM_CAPACITIES_VECTOR", "INVALID_TEAM_ID is reserved, and cannot be used in the team capacities vector."),
            253 to BlazeErrorDef("GAMEMANAGER_ERR_TEAM_NOT_ALLOWED", "trying to perform a team operation on a game or player for a team that isn't allowed (not present in capacity vector)"),
            254 to BlazeErrorDef("GAMEMANAGER_ERR_TOTAL_TEAM_CAPACITY_INVALID", "sum of all teams is not equal to the game's total capacity."),
            255 to BlazeErrorDef("GAMEMANAGER_ERR_TEAM_FULL", "trying to join a full team, or a team that you cannot fit your entire game group into."),
            257 to BlazeErrorDef("GAMEMANAGER_ERR_PLAYER_CAPACITY_NOT_EVENLY_DIVISIBLE_BY_TEAMS", "A game's total player capacity must be evenly divisible amongst the teams present in the game."),
            270 to BlazeErrorDef("GAMEMANAGER_ERR_EMPTY_ROLE_CAPACITIES", "Role capacities were empty."),
            271 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_CAPACITY_TOO_SMALL", "Sum of role capacities were too small to complete a team."),
            272 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_CAPACITY_TOO_LARGE", "A role's capacity was specified as larger than the game's team capacity."),
            273 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_NOT_ALLOWED", "Operation on a role not present in the game."),
            274 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_FULL", "The selected role is full."),
            275 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_CRITERIA_INVALID", "The game failed to parse the role criteria."),
            276 to BlazeErrorDef("GAMEMANAGER_ERR_ROLE_CRITERIA_FAILED", "The player's joinGame failed; he doesn't satisfy the game's RoleCriteria formula.  See the JoinGameCb's entry criteria string for details."),
            277 to BlazeErrorDef("GAMEMANAGER_ERR_MULTI_ROLE_CRITERIA_INVALID", "The game failed to parse the multirole criteria."),
            278 to BlazeErrorDef("GAMEMANAGER_ERR_MULTI_ROLE_CRITERIA_FAILED", "The player's joinGame failed; he doesn't satisfy the game's MultiRoleCriteria formula."),
            301 to BlazeErrorDef("GAMEMANAGER_ERR_NO_DEDICATED_SERVER_FOUND", "No dedicated game servers were found (none are available to reset)."),
            302 to BlazeErrorDef("GAMEMANAGER_ERR_DEDICATED_SERVER_ONLY_ACTION", "An invalid action was attempted, this action is only available for dedicated server network topology"),
            303 to BlazeErrorDef("GAMEMANAGER_ERR_DEDICATED_SERVER_HOST_CANNOT_JOIN", "Host can't join his own dedicated server game."),
            304 to BlazeErrorDef("GAMEMANGER_ERR_MACHINE_ID_LIST_EMPTY", "A dynamic dedicated server creator attempted to register itself with no machine ids provided"),
            308 to BlazeErrorDef("GAMEMANAGER_ERR_NO_HOSTS_AVAILABLE_FOR_INJECTION", "Virtual game materialization failed because suitable dedicated server for game injection wasn't found."),
            401 to BlazeErrorDef("GAMEBROWSER_ERR_INVALID_CRITERIA", "Problem parsing your game browsing criteria.  See GetGameListError's err msg for details."),
            402 to BlazeErrorDef("GAMEBROWSER_ERR_INVALID_CAPACITY", "A list's capacity must be GAME_LIST_CAPACITY_UNLIMITED, or greater than zero."),
            403 to BlazeErrorDef("GAMEBROWSER_ERR_INVALID_LIST_ID", "No list subscription found on the blazeServer with the supplied id."),
            404 to BlazeErrorDef("GAMEBROWSER_ERR_NOT_LIST_OWNER", "This operation can only be completed by the list owner."),
            405 to BlazeErrorDef("GAMEBROWSER_ERR_INVALID_LIST_CONFIG_NAME", "The gameBrowser can't find a list configuration with the supplied listConfigName.  (list configurations are defined in the server's gamebrowser config file)."),
            406 to BlazeErrorDef("GAMEBROWSER_ERR_CANNOT_GET_USERSET", "Cannot get user set from userset provider"),
            407 to BlazeErrorDef("GAMEBROWSER_ERR_EXCEED_MAX_SYNC_SIZE", "Cannot get games exceed max size set based on configs maxGameListSyncSize"),
            408 to BlazeErrorDef("GAMEBROWSER_ERR_EXCEEDED_MAX_REQUESTS", "The number of concurrent active game browser lists exceeded configured maximum."),
            409 to BlazeErrorDef("GAMEBROWSER_ERR_SEARCH_ERR_OVERLOADED", "The search slave is overloaded."),
            410 to BlazeErrorDef("GAMEBROWSER_ERR_CROSS_PLATFORM_OPTOUT", "Action not allowed for user opted-out of cross platform."),
            411 to BlazeErrorDef("GAMEBROWSER_ERR_DISALLOWED_PLATFORM", "The action requested required a disallowed cross platform interaction."),
            502 to BlazeErrorDef("GAMEMANAGER_ERR_GAME_CAPACITY_TOO_SMALL", "In valid game capacity settings, the desired capacity of the game to be created is less than the number of people that need to join the game."),
            503 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_ACTION_FOR_GROUP", "An invalid action was attempted, this action is only available for individual player instead of a group."),
            505 to BlazeErrorDef("GAMEMANAGER_ERR_MIGRATION_NOT_SUPPORTED", "An attempt to initiate host migration has occured on a game that does not support host migration."),
            506 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_NEWHOST", "Suggested new host is a invalid candidate for host migration."),
            508 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_PERSISTED_GAME_ID_OR_SECRET", "The secret does not match with the guid."),
            509 to BlazeErrorDef("GAMEMANAGER_ERR_PERSISTED_GAME_ID_IN_USE", "The persisted game id is in use."),
            510 to BlazeErrorDef("GAMEMANAGER_ERR_USER_NOT_FOUND", ""),
            511 to BlazeErrorDef("GAMEMANAGER_ERR_USER_ALREADY_AUDITED", ""),
            512 to BlazeErrorDef("GAMEMANAGER_ERR_USER_CURRENTLY_AUDITED", ""),
            600 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_SCENARIO_NAME", "The scenario name provided does not exist."),
            601 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_SCENARIO_ID", "The scenario id provided is invalid, or no longer exists."),
            602 to BlazeErrorDef("GAMEMANAGER_ERR_NOT_SCENARIO_OWNER", "Attempting to perform an action on a scenario not owned by the current user."),
            603 to BlazeErrorDef("GAMEMANAGER_ERR_MISSING_SCENARIO_ATTRIBUTE", "The Scenario being run requires an attribute that was not provided."),
            604 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_SCENARIO_ATTRIBUTE", "A Scenario Attribute being used is currently invalid. (Generally indicates a config setup error.)"),
            605 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_SCENARIO_VARIANT", "The Scenario variant being used is currently invalid."),
            610 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_TEMPLATE_NAME", "The RPC template name provided does not exist."),
            611 to BlazeErrorDef("GAMEMANAGER_ERR_MISSING_TEMPLATE_ATTRIBUTE", "The template being run requires an attribute that was not provided."),
            612 to BlazeErrorDef("GAMEMANAGER_ERR_INVALID_TEMPLATE_ATTRIBUTE", "A template Attribute being used is currently invalid. (Generally indicates a config setup error.)"),
            620 to BlazeErrorDef("GAMEMANAGER_ERR_INPUT_SANITIZER_FAILURE", "The Input Sanitizer failed due to incorrect formatting or criteria failure."),
            700 to BlazeErrorDef("GAMEMANAGER_ERR_EXTERNAL_SERVICE_BUSY", "The number of calls by the user for has exceeded the command's rate limit."),
            701 to BlazeErrorDef("GAMEMANAGER_ERR_EXTERNAL_SESSION_IMAGE_INVALID", "The image for the external session is invalid or missing."),
            702 to BlazeErrorDef("GAMEMANAGER_ERR_EXTERNAL_SESSION_CUSTOM_DATA_TOO_LARGE", "The custom data for the external session is too large."),
            703 to BlazeErrorDef("GAMEMANAGER_ERR_EXTERNAL_SESSION_ERROR", "General error returned when the external session service returns an unhandled error."),
            704 to BlazeErrorDef("GAMEMANAGER_ERR_EXTERNALSESSION_INVALID_SANDBOX_ID", "The external session has invalid sandbox id."),
        ),
        "Redirector" to mapOf(
            1 to BlazeErrorDef("REDIRECTOR_SERVER_NOT_FOUND", "No Blaze cluster found matching the requested service name (getServerInstance/getServerInstanceHttp calls only)"),
            2 to BlazeErrorDef("REDIRECTOR_NO_SERVER_CAPACITY", "All endpoints matching the requested service name and connection profile have reached their connection limit (or are draining)"),
            3 to BlazeErrorDef("REDIRECTOR_NO_MATCHING_INSTANCE", "No endpoints found matching the requested service name and connection profile"),
            4 to BlazeErrorDef("REDIRECTOR_SERVER_NAME_ALREADY_IN_USE", "(updateServerInfo/publishServerInstanceInfo calls only) A Blaze instance with the same instance id is already registered (under a different registration id) for the specified service name"),
            5 to BlazeErrorDef("REDIRECTOR_CLIENT_NOT_COMPATIBLE", "The client is incompatible with the Blaze cluster matching the requested service name (the client version is in the cluster's configured list of incompatible client versions)"),
            6 to BlazeErrorDef("REDIRECTOR_CLIENT_UNKNOWN", "The client version is not recognized by the Blaze cluster matching the requested service name (the client version is not in the cluster's configured lists of compatible or incompatible client versions, and the cluster's list of compatible client versions is non-empty)"),
            7 to BlazeErrorDef("REDIRECTOR_UNKNOWN_CONNECTION_PROFILE", "The requested connection profile is not in the redirector's configured list of profiles"),
            8 to BlazeErrorDef("REDIRECTOR_SERVER_SUNSET", "The requested service name has been sunset"),
            9 to BlazeErrorDef("REDIRECTOR_SERVER_DOWN", "The REDIRECTOR_SERVER_DOWN error code is no longer in use"),
            10 to BlazeErrorDef("REDIRECTOR_INVALID_PARAMETER", "The REDIRECTOR_INVALID_PARAMETER error code is no longer in use"),
            11 to BlazeErrorDef("REDIRECTOR_UNKNOWN_SERVICE_NAME", "No Blaze cluster found matching the requested service name (scheduleServerDowntime calls only)"),
            12 to BlazeErrorDef("REDIRECTOR_PAST_EVENT", "(scheduleServerDowntime calls only) The downtime being scheduled has already begun"),
            13 to BlazeErrorDef("REDIRECTOR_UNKNOWN_SCHEDULE_ID", "(cancelServerDowntime calls only) No scheduled downtime found matching the requested id"),
            14 to BlazeErrorDef("REDIRECTOR_MISSING_SERVICE_NAME", "(findCACertificates calls only) Request specified a DirtyCert version without providing a service name"),
        ),
        "Stats" to mapOf(
            1 to BlazeErrorDef("STATS_ERR_CONFIG_NOTAVAILABLE", "Config data is not loaded"),
            2 to BlazeErrorDef("STATS_ERR_INVALID_LEADERBOARD_ID", "Invalid leaderboard ID"),
            3 to BlazeErrorDef("STATS_ERR_INVALID_FOLDER_ID", "Invalid leaderboard folder ID"),
            4 to BlazeErrorDef("STATS_ERR_UNKNOWN_CATEGORY", "Unknown category was requested"),
            5 to BlazeErrorDef("STATS_ERR_STAT_NOT_FOUND", "Stat not found"),
            6 to BlazeErrorDef("STATS_ERR_BAD_PERIOD_TYPE", "Bad period type"),
            7 to BlazeErrorDef("STATS_ERR_NO_DB_CONNECTION", "Failed to obtain DB connection"),
            8 to BlazeErrorDef("STATS_ERR_DB_DATA_NOT_AVAILABLE", "No data returned by DB"),
            9 to BlazeErrorDef("STATS_ERR_UNKNOWN_STAT_GROUP", "Unknown stat group"),
            10 to BlazeErrorDef("STATS_ERR_DB_TRANSACTION_ERROR", "Unsuccessful DB transaction"),
            11 to BlazeErrorDef("STATS_ERR_INVALID_UPDATE_TYPE", "Invalid update type"),
            13 to BlazeErrorDef("STATS_ERR_DB_QUERY_FAILED", "DB query select failed"),
            14 to BlazeErrorDef("STATS_ERR_RANK_OUT_OF_RANGE", "Rank out of range"),
            15 to BlazeErrorDef("STATS_ERR_BAD_PERIOD_OFFSET", "Bad period offset"),
            16 to BlazeErrorDef("STATS_ERR_BAD_SCOPE_INFO", "Scope defination is not right."),
            17 to BlazeErrorDef("STATS_ERR_INVALID_FOLDER_NAME", "Requested folder is not found."),
            18 to BlazeErrorDef("STATS_ERR_OPERATION_IN_PROGRESS", "Requested operation is already in progress."),
            20 to BlazeErrorDef("STATS_ERR_INVALID_OPERATION", "Requested operation is not defined"),
            21 to BlazeErrorDef("STATS_ERR_INVALID_OBJECT_ID", "Invalid object ID is supplied"),
            22 to BlazeErrorDef("STATS_ERR_BAD_PERIOD_COUNTER", "Invalid period counter is supplied"),
            23 to BlazeErrorDef("STATS_ERR_LEADERBOARD_NOT_IN_MEMORY", "Leaderboard is not in the memory"),
        ),
        "Util" to mapOf(
            100 to BlazeErrorDef("UTIL_CONFIG_NOT_FOUND", "config section not found"),
            101 to BlazeErrorDef("UTIL_PSU_LIMIT_EXCEEDED", "PSU limit reached"),
            102 to BlazeErrorDef("UTIL_SERVICENAME_NOT_SPECIFIED", "Caller did not specify a service name. Required for shared platforms cluster."),
            103 to BlazeErrorDef("UTIL_SERVICENAME_NOT_HOSTED", "Caller specified service name is not hosted on this instance."),
            104 to BlazeErrorDef("UTIL_CALLER_PLATFORM_NOT_FOUND", "caller's platform is not available."),
            105 to BlazeErrorDef("UTIL_CALLER_PLATFORM_MISMATCH", "caller is attempting to access a resource for a different platform. Explicit error mostly to assist debugging."),
            106 to BlazeErrorDef("UTIL_CALLER_PLATFORM_NOT_ALLOWED", "caller is attempting to access a service it should not. Explicit error mostly to assist debugging."),
            150 to BlazeErrorDef("UTIL_TELEMETRY_NO_SERVERS_AVAILABLE", "There are no telemetry servers available"),
            151 to BlazeErrorDef("UTIL_TELEMETRY_OUT_OF_MEMORY", "Server is out of memory."),
            152 to BlazeErrorDef("UTIL_TELEMETRY_KEY_TOO_LONG", "Telemetry key is longer then it should be."),
            155 to BlazeErrorDef("UTIL_TICKER_NO_SERVERS_AVAILABLE", "There are no ticker servers available."),
            156 to BlazeErrorDef("UTIL_TICKER_KEY_TOO_LONG", "Ticker key is too long to create."),
            200 to BlazeErrorDef("UTIL_USS_RECORD_NOT_FOUND", "Record not found in user small storage."),
            201 to BlazeErrorDef("UTIL_USS_TOO_MANY_KEYS", "Exceeded number of keys allowed for user."),
            202 to BlazeErrorDef("UTIL_USS_DB_ERROR", "Database error while reading/writing."),
            250 to BlazeErrorDef("UTIL_USS_USER_NO_EXTENDED_DATA", "There is no extended data for the given session."),
            300 to BlazeErrorDef("UTIL_SUSPEND_PING_TIME_TOO_LARGE", "Requested Ping Suspension time exceeds maximum configured time."),
            301 to BlazeErrorDef("UTIL_SUSPEND_PING_TIME_TOO_SMALL", "Requested Ping Suspension time is less than the minimum time allowed for a connection (has to be greater than inactivityTimeout on the BlazeServer)."),
        ),
        "Messaging" to mapOf(
            1 to BlazeErrorDef("MESSAGING_ERR_UNKNOWN", "Unknown error occurred."),
            2 to BlazeErrorDef("MESSAGING_ERR_MAX_ATTR_EXCEEDED", "Exceeded maximum number of message attributes."),
            3 to BlazeErrorDef("MESSAGING_ERR_DATABASE", "Messaging database error."),
            4 to BlazeErrorDef("MESSAGING_ERR_TARGET_NOT_FOUND", "Message target not found."),
            5 to BlazeErrorDef("MESSAGING_ERR_TARGET_TYPE_INVALID", "Message target type is invalid."),
            6 to BlazeErrorDef("MESSAGING_ERR_TARGET_INBOX_FULL", "Target message inbox is full."),
            7 to BlazeErrorDef("MESSAGING_ERR_MATCH_NOT_FOUND", "Match not found."),
            8 to BlazeErrorDef("MESSAGING_ERR_FEATURE_DISABLED", "Feature is disabled on the messaging server."),
            9 to BlazeErrorDef("MESSAGING_ERR_INVALID_PARAM", "Invalid parameter(s)."),
            10 to BlazeErrorDef("MESSAGING_ERR_PROFANITY_SYSTEM", "Message was tagged for profanity filtering but the profanity service returned an error. Message will not be delivered."),
        ),
        "AssociationLists" to mapOf(
            1 to BlazeErrorDef("ASSOCIATIONLIST_ERR_USER_NOT_FOUND", "The referenced user was not found."),
            2 to BlazeErrorDef("ASSOCIATIONLIST_ERR_DUPLICATE_USER_FOUND", "Duplicate ListMemberIds were found from the UpdateListMembersRequest."),
            3 to BlazeErrorDef("ASSOCIATIONLIST_ERR_CANNOT_INCLUDE_SELF", "User cannot include themselves in a UpdateListMembersRequest."),
            4 to BlazeErrorDef("ASSOCIATIONLIST_ERR_INVALID_USER", "A ListMemberId in the request is invalid. The blaze id, external id, and persona are all invalid."),
            5 to BlazeErrorDef("ASSOCIATIONLIST_ERR_MEMBER_ALREADY_IN_THE_LIST", "Some members in the UpdateListMembersRequest are already in the association list."),
            6 to BlazeErrorDef("ASSOCIATIONLIST_ERR_MEMBER_NOT_FOUND_IN_THE_LIST", "Some members in the UpdateListMembersRequest were not found in the association list."),
            10 to BlazeErrorDef("ASSOCIATIONLIST_ERR_LIST_NOT_FOUND", "Specified list does not exist or no list is specified."),
            11 to BlazeErrorDef("ASSOCIATIONLIST_ERR_LIST_IS_FULL_OR_TOO_MANY_USERS", "List is already full, can't add other members, or members in the list to be added are too many for the list max size. Used when FIFO for list is false"),
            16 to BlazeErrorDef("ASSOCIATIONLIST_ERR_PAIRED_LIST_MODIFICATION_NOT_SUPPORTED", "User can not modify the Paired list(add/remove members) directly."),
            17 to BlazeErrorDef("ASSOCIATIONLIST_ERR_PAIRED_LIST_IS_FULL_OR_TOO_MANY_USERS", "Paired list is already full."),
            18 to BlazeErrorDef("ASSOCIATIONLIST_ERR_SUBSCRIBE_USER_LIST_NOT_SUPPORTED", "Requestor can not subscribe/unsubscribe another user's list."),
        ),
        "GameReporting" to mapOf(
            1 to BlazeErrorDef("GAMEREPORTING_ERR_UNEXPECTED_REPORT", ""),
            100 to BlazeErrorDef("GAMEREPORTING_COLLATION_ERR_NO_VALID_REPORTS", ""),
            101 to BlazeErrorDef("GAMEREPORTING_COLLATION_ERR_NO_REPORTS", ""),
            102 to BlazeErrorDef("GAMEREPORTING_COLLATION_REPORTS_INCONSISTENT", ""),
            103 to BlazeErrorDef("GAMEREPORTING_COLLATION_ERR_MISSING_GAME_ATTRIBUTE", ""),
            104 to BlazeErrorDef("GAMEREPORTING_COLLATION_ERR_INVALID_GAME_ATTRIBUTE", ""),
            200 to BlazeErrorDef("GAMEREPORTING_CUSTOM_ERR_PROCESSING_FAILED", ""),
            201 to BlazeErrorDef("GAMEREPORTING_CONFIG_ERR_MISSING_PROCESSOR_ATTRIBUTE", ""),
            202 to BlazeErrorDef("GAMEREPORTING_CONFIG_ERR_INVALID_PROCESSOR_ATTRIBUTE", ""),
            203 to BlazeErrorDef("GAMEREPORTING_CONFIG_ERR_STAT_UPDATE_FAILED", ""),
            204 to BlazeErrorDef("GAMEREPORTING_CUSTOM_ERR_PROCESS_UPDATED_STATS_FAILED", ""),
            205 to BlazeErrorDef("GAMEREPORTING_ERR_INVALID_GAME_TYPE", ""),
            301 to BlazeErrorDef("GAMEREPORTING_OFFLINE_ERR_INVALID_GAME_TYPE", ""),
            302 to BlazeErrorDef("GAMEREPORTING_OFFLINE_ERR_REPORT_INVALID", ""),
            401 to BlazeErrorDef("GAMEREPORTING_TRUSTED_ERR_INVALID_GAME_TYPE", ""),
            402 to BlazeErrorDef("GAMEREPORTING_TRUSTED_ERR_REPORT_INVALID", ""),
            501 to BlazeErrorDef("GAMEHISTORY_ERR_UNKNOWN_QUERY", "Game report query requested is not defined."),
            502 to BlazeErrorDef("GAMEHISTORY_ERR_INVALID_COLUMNKEY", "Game report query requested is not defined."),
            503 to BlazeErrorDef("GAMEHISTORY_ERR_INVALID_FILTER", "Game report query requested is not defined."),
            504 to BlazeErrorDef("GAMEHISTORY_ERR_INVALID_GAMETYPE", "Game report query requested is not defined."),
            505 to BlazeErrorDef("GAMEHISTORY_ERR_UNKNOWN_VIEW", "Game report view requested is not defined."),
            506 to BlazeErrorDef("GAMEHISTORY_ERR_INVALID_QUERY", "Game report query requested is invalid."),
            507 to BlazeErrorDef("GAMEHISTORY_ERR_MISSING_QVARS", "Query variables are needed but not provided."),
            508 to BlazeErrorDef("GAMEHISTORY_ERR_INVALID_QVARS", "Query variables provided are invalid."),
        ),
        "Friends" to mapOf(
            504 to BlazeErrorDef("FRIENDS_UNKNOWN_ERR", "An unknown error occurred within the server"),
            901 to BlazeErrorDef("FRIENDS_NO_SUCH_USER", "Unable to locate a user with the specified ID"),
            909 to BlazeErrorDef("FRIENDS_INVALID_ARGUMENT_TYPE", "Invalid type"),
            11100 to BlazeErrorDef("FRIENDS_API_KEY_INVALID", "Requires API Key or Client Certificate"),
            20006 to BlazeErrorDef("FRIENDS_NO_ID_SPECIFIED", "Neither a Nucleus ID nor a Persona ID were passed to a method that expected one"),
            20007 to BlazeErrorDef("FRIENDS_NO_FRIEND_SPECIFIED", "No friend ID was specified"),
            20008 to BlazeErrorDef("FRIENDS_BAD_PRIVACY_SETTING", "An invalid privacy setting was specified"),
            22001 to BlazeErrorDef("FRIENDS_FRIENDS_LIST_FULL", "The inviter or invitee's friends list is at or above the limit"),
            22002 to BlazeErrorDef("FRIENDS_NO_GROUP_NAME_SPECIFIED", "No group name was specified when trying to remove a user from a group"),
            22003 to BlazeErrorDef("FRIENDS_GLOBAL_GROUP_LOCKED", "Can not remove a user from the global group"),
            22004 to BlazeErrorDef("FRIENDS_AUTHTOKEN_INVALID", "The AuthToken in the request is invalid"),
            22005 to BlazeErrorDef("FRIENDS_AUTHTOKEN_INVALID_FOR_USER", "The AuthToken does not match the Nucleus ID"),
            22006 to BlazeErrorDef("FRIENDS_INVITATION_NOT_FOUND", "The specified invitation was not found"),
            22007 to BlazeErrorDef("FRIENDS_TARGET_NOT_FRIEND", "The target user is not a friend"),
            22008 to BlazeErrorDef("FRIENDS_TARGET_IN_CUSTOM_GROUP", "The target user is in a non-default group and must be removed"),
            22009 to BlazeErrorDef("FRIENDS_INVITEE_BLOCKED_BY_INVITER", "The invitee is in the inviter's block list"),
            22010 to BlazeErrorDef("FRIENDS_INVITEE_ALREADY_FRIEND", "The invitee is already in the inviter's friend list"),
            22013 to BlazeErrorDef("FRIENDS_FRIEND_NOT_IN_GROUP", "The friend isn't in the specified group"),
            22015 to BlazeErrorDef("FRIENDS_BLOCKING_SELF", "The user is trying to block their own ID"),
            22016 to BlazeErrorDef("FRIENDS_BATCH_INVITE_ERROR", "An error was encountered while doing a batch invite operation"),
            22017 to BlazeErrorDef("FRIENDS_INVITEE_IS_INVITER", "The user is trying to invite their own ID"),
            22018 to BlazeErrorDef("FRIENDS_ID_LIST_EMPTY", "The specified ID list is empty"),
            22020 to BlazeErrorDef("FRIENDS_OUTBOUND_INVITES_FULL", "The user's outbound invite list is full"),
            22021 to BlazeErrorDef("FRIENDS_INBOUND_INVITES_FULL", "The user's inbound invite list is full"),
            22022 to BlazeErrorDef("FRIENDS_FAVORITING_SELF", "You can't favorite yourself"),
            22023 to BlazeErrorDef("FRIENDS_UNFAVORITING_SELF", "You can't unfavorite yourself"),
            22024 to BlazeErrorDef("FRIENDS_FAVORITING_NON_FRIEND", "You can't favorite a user who is not a friend"),
            22025 to BlazeErrorDef("FRIENDS_UNFAVORITING_NON_FRIEND", "You can't unfavorite a user who is not a friend"),
            22026 to BlazeErrorDef("FRIENDS_NAMESPACE_MISTMATCH", "The namespaces don't match for the Persona IDs"),
        ),
        "UserSessions" to mapOf(
            1 to BlazeErrorDef("USER_ERR_USER_NOT_FOUND", "The referenced user was not found."),
            2 to BlazeErrorDef("USER_ERR_SESSION_NOT_FOUND", "The referenced session was not found."),
            3 to BlazeErrorDef("USER_ERR_DUPLICATE_SESSION", "The session could not be added because one from that user already exists."),
            4 to BlazeErrorDef("USER_ERR_NO_EXTENDED_DATA", "The extended data could not be returned because there is no extended data for the given session"),
            5 to BlazeErrorDef("USER_ERR_MAX_DATA_REACHED", "The extended data attribute could not be added because the maximum number of attributes has been reached for this session"),
            6 to BlazeErrorDef("USER_ERR_KEY_NOT_FOUND", "The extended data attribute could not be removed because key was not found"),
            7 to BlazeErrorDef("USER_ERR_INVALID_SESSION_INSTANCE", "The session did not belong to the calling instance."),
            8 to BlazeErrorDef("USER_ERR_INVALID_PARAM", "Invalid parameter(s)."),
            9 to BlazeErrorDef("USER_ERR_MINIMUM_CHARACTERS", "The minimum of characters is 3."),
            10 to BlazeErrorDef("ACCESS_GROUP_ERR_INVALID_GROUP", "The specified access group was not found."),
            11 to BlazeErrorDef("ACCESS_GROUP_ERR_DEFAULT_GROUP", "The specified access group is default group for the referenced user."),
            12 to BlazeErrorDef("ACCESS_GROUP_ERR_NOT_CURRENT_GROUP", "The referenced user does not belong to the specified group."),
            13 to BlazeErrorDef("ACCESS_GROUP_ERR_CURRENT_GROUP", "The referenced user already belong to the specified group."),
            14 to BlazeErrorDef("ACCESS_GROUP_ERR_NO_GROUP_FOUND", "There is no group is found for specified external id and client type."),
            15 to BlazeErrorDef("GEOIP_INCOMPLETE_PARAMETERS", "Parameters in GeoIp request are incomplete: city, state region and country must be supplied."),
            16 to BlazeErrorDef("USER_ERR_GEOIP_LOOKUP_FAILED", "GeoIp lookup failed. Returned to the caller so they can take action, e.g., region selection."),
            17 to BlazeErrorDef("ERR_ENTITY_TYPE_NOT_FOUND", "The entity type is not recognized by the component."),
            18 to BlazeErrorDef("ERR_ENTITY_NOT_FOUND", "no entity is found matching the type name and name provided."),
            19 to BlazeErrorDef("ERR_NOT_SUPPORTED", "the entity provided is recognized, but searching by name is not supported."),
            20 to BlazeErrorDef("USER_ERR_EXISTS", "A duplicate user already exists"),
            23 to BlazeErrorDef("GEOIP_ERR_USER_OPTOUT", "The requested user with opt-in field disabled."),
            30 to BlazeErrorDef("USER_ERR_CROSS_PLATFORM_OPTOUT", "Action not allowed for user opted-out of cross platform."),
            31 to BlazeErrorDef("USER_ERR_DISALLOWED_PLATFORM", "The action requested required a disallowed cross platform interaction."),
        ),
    )
}
